//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dflow_Inventory.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Parameter
    {
        public int applicationParameterId { get; set; }
        public string companyName { get; set; }
        public string dealsIn { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string mobileNo1 { get; set; }
        public string mobileNo2 { get; set; }
        public string emailAddress1 { get; set; }
        public string emailAddress2 { get; set; }
        public string panNumber { get; set; }
        public string hsnCode { get; set; }
        public string gstNumber { get; set; }
    }
}
