//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dflow_Inventory.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inventory_DflowEntities : DbContext
    {
        public Inventory_DflowEntities()
            : base("name=Inventory_DflowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Item_Master> Item_Master { get; set; }
        public DbSet<Unit_Master> Unit_Master { get; set; }
        public DbSet<Customer_Master> Customer_Master { get; set; }
        public DbSet<Supplier_Master> Supplier_Master { get; set; }
    }
}
