//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dflow_Inventory.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inventory_DflowEntities : DbContext
    {
        public Inventory_DflowEntities()
            : base("name=Inventory_DflowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Item_Master> Item_Master { get; set; }
        public DbSet<Unit_Master> Unit_Master { get; set; }
        public DbSet<Customer_Master> Customer_Master { get; set; }
        public DbSet<Supplier_Master> Supplier_Master { get; set; }
        public DbSet<Designation> Designations { get; set; }
        public DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Employment_Status> Employment_Status { get; set; }
        public DbSet<Distributor_Master> Distributor_Master { get; set; }
        public DbSet<Vendor_Master> Vendor_Master { get; set; }
        public DbSet<PurchaseHeader> PurchaseHeaders { get; set; }
        public DbSet<customerType> customerTypes { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<marital_Status> marital_Status { get; set; }
        public DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public DbSet<InvoiceHeader> InvoiceHeaders { get; set; }
        public DbSet<User_Group> User_Group { get; set; }
        public DbSet<User_Master> User_Master { get; set; }
        public DbSet<Expense_Master> Expense_Master { get; set; }
        public DbSet<FinancialYear> FinancialYears { get; set; }
        public DbSet<PaymentMode> PaymentModes { get; set; }
        public DbSet<voucherHeader> voucherHeaders { get; set; }
    }
}
