//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dflow_Inventory.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHeader
    {
        public InvoiceHeader()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int invoiceId { get; set; }
        public string invoiceNumber { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public int customerId { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> taxableAmount { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public int entryBy { get; set; }
        public System.DateTime entryDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string finYear { get; set; }
        public Nullable<decimal> cgstPercent { get; set; }
        public Nullable<decimal> cgstAmount { get; set; }
        public Nullable<decimal> sgstPercent { get; set; }
        public Nullable<decimal> sgstAmount { get; set; }
        public string amountInWords { get; set; }
    
        public virtual Customer_Master CustomerMaster { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
