//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dflow_Inventory.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMode
    {
        public PaymentMode()
        {
            this.voucherHeaders = new HashSet<voucherHeader>();
        }
    
        public string paymentCode { get; set; }
        public string paymentDescription { get; set; }
    
        public virtual ICollection<voucherHeader> voucherHeaders { get; set; }
    }
}
