//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dflow_Inventory.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int userId { get; set; }
        public string name { get; set; }
        public string mobileNumber { get; set; }
        public string emailId { get; set; }
        public string loginId { get; set; }
        public string loginKey { get; set; }
        public int userGroupId { get; set; }
        public bool active { get; set; }
        public int entryBy { get; set; }
        public System.DateTime entryDate { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
    }
}
