//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dflow_Inventory.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucherHeader
    {
        public int voucherId { get; set; }
        public string voucherNumber { get; set; }
        public System.DateTime voucherDate { get; set; }
        public string invoiceNo { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string paymentMode { get; set; }
        public string bankName { get; set; }
        public string chequeNo { get; set; }
        public Nullable<System.DateTime> chequeDate { get; set; }
        public int entryBy { get; set; }
        public System.DateTime entryDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string finYear { get; set; }
        public string narration { get; set; }
    
        public virtual PaymentMode PaymentMode1 { get; set; }
    }
}
